version: '3'
services:
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8080:8080"
    environment:
      - APP_DSN=postgres://db/user?sslmode=disable&user=postgres&password=postgres
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "user"
    ports:
      - 5432:5432
