version: '3.6'
services:
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8080:8080"
    environment:
      - APP_DSN=postgres://db/test_users?sslmode=disable&user=postgres&password=postgres
      - APP_BROKER=kafka:9092
      - APP_REDIS_ADDR=redis:6379
    depends_on:
      - kafka
    links:
      - kafka
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "test_users"
    ports:
      - 5432:5432
  clickhouse-server:
    image: yandex/clickhouse-server
    volumes:
      - ./deploy/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./deploy/clickhouse/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - ./deploy/shared/ch-data/clickhouse:/var/lib/clickhouse
    depends_on:
      - kafka
    links:
      - kafka
    ports:
      - 8123:8123
      - 9000:9000

  init-clickhouse:
    image: yandex/clickhouse-client
    depends_on:
      - clickhouse-server
    volumes:
      - ./deploy/clickhouse/schema.sql:/schema.sql
    entrypoint:
      - bash
      - -c
      - clickhouse-client --host clickhouse-server -mn < /schema.sql

  clickhouse-client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "users:1:1"
      ALLOW_PLAINTEXT_LISTENER: "yes"

